identifier_name:
  allowed_symbols: "_"
  min_length: 2
  severity: warning
  validates_start_with_lowercase: false

trailing_whitespace:
  ignores_empty_lines: true

force_cast:
  severity: error

force_try:
  severity: error

function_body_length:
  warning: 100
  error: 150
  
cyclomatic_complexity:
  ignores_case_statements: true
    
line_length: 150
